using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using UnityEngine;
using UnityEngine.UI;

public class LanguageChangeHandler : MonoBehaviour
{
	[CompilerGenerated]
	private sealed class _003CStart_003Ed__3 : IEnumerator<object>, IEnumerator, IDisposable
	{
		private int _003C_003E1__state;

		private object _003C_003E2__current;

		public LanguageChangeHandler _003C_003E4__this;

		object IEnumerator<object>.Current
		{
			[DebuggerHidden]
			get
			{
				return null;
			}
		}

		object IEnumerator.Current
		{
			[DebuggerHidden]
			get
			{
				return null;
			}
		}

		[DebuggerHidden]
		public _003CStart_003Ed__3(int _003C_003E1__state)
		{
		}

		[DebuggerHidden]
		void IDisposable.Dispose()
		{
		}

		private bool MoveNext()
		{
			return false;
		}

		bool IEnumerator.MoveNext()
		{
			//ILSpy generated this explicit interface implementation from .override directive in MoveNext
			return this.MoveNext();
		}

		[DebuggerHidden]
		void IEnumerator.Reset()
		{
		}
	}

	[SerializeField]
	private Text languageName;

	private void OnEnable()
	{
	}

	private void LocaleManager_OnLocaleChangedEvent(Locale obj)
	{
	}

	[IteratorStateMachine(typeof(_003CStart_003Ed__3))]
	private IEnumerator Start()
	{
		return null;
	}

	private void OnDisable()
	{
	}

	public void OnNextButtonPressed(Transform ClickedButton)
	{
	}

	public void OnPreviousButtonPressed(Transform ClickedButton)
	{
	}
}
